name: JuhoIsola
favicon: null
layout_spectrum: 0.72186
typography_spectrum: 0.6705558691173792
title: "Juho Isola's homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f4f5e7'
    - '#2a4a29'
    - '#73ab2e'
    - '#ae6c65'
  brandStrength: 0.1875
  lightness: 0.7071151847485453
  saturation: 0
  rhythmicContrast: 0.42441326449625194
purpose: []
