name: JuhoIsola
favicon: null
layout_spectrum: 0.6147
typography_spectrum: 0.6705558691173792
title: "Juho Isola's homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15151e'
    - '#6abcd9'
    - '#6f5d53'
    - '#bfb099'
  brandStrength: 0.1875
  lightness: 0.7071151847485453
  saturation: 0.0625
  rhythmicContrast: 0.42441326449625194
purpose: []
