name: JuhoIsola
favicon: null
layout_spectrum: 0.58698
typography_spectrum: 0.33755
title: "Juho Isola's homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#19b1ce'
    - '#484848'
    - '#ffb174'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
