name: JuhoIsola
favicon: null
layout_spectrum: 0.7302345454227179
typography_spectrum: 0.6705558691173792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11780637153424323
  lightness: 0.7071151847485453
  saturation: 0.008994384435936809
  rhythmicContrast: 0.42441326449625194
purpose: []
