name: JuhoIsola
favicon: null
layout_spectrum: 0.64115
typography_spectrum: 0.38212
title: "Juho Isola's homepage"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71779736-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00bedc'
    - '#ffffff'
    - '#007689'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
