name: JuhoIsola
favicon: null
layout_spectrum: 0.07391
typography_spectrum: 0.82059
title: Juho Isola's homepage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71779736-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00bedc'
    - '#ffffff'
    - '#007689'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
